apiVersion: batch/v1
kind: CronJob
metadata:
  name: bem-vindo
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.36
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo bem-vindo ao trabalho
          restartPolicy: OnFailure
